### ISSUE TITLE
Location input

### ISSUE THREAD

**Issue by tomgw** [Aygath/zon#4]
Great program! just what I needed on my boat. Thanks! It would be nice if I can input my location coordinates in an other format (decimal degrees, NMEA format etc) but I'm happy already. :-)

**Comment by Aygath** [comment]
I write this down as a feature request, not a bug. I am working on the feature. The program will read 1) decimal degrees (from Google maps) and 2) it will grab the location off the zone1970.tab file, as indicated by the users timezone (more useful default than 0N, 0W
